export const FETCH_HISTORY_REQUEST = 'FETCH_HISTORY_REQUEST'
export const FETCH_HISTORY_SUCESS = 'FETCH_HISTORY_SUCESS'
export const FETCH_HISTORY_FAILURE = 'FETCH_HISTORY_FAILURE'
export const UPDATE_FILTER = 'UPDATE_FILTER'
